baseurl = "https://nqthqn.com/"
title = "nqthqn"
author = "Nate Nichols"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
publishDir = "docs"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "nqthqn"

[[menu.main]]
    name = "Github"
    url  = "https://github.com/nqthqn/"

